model: # VQ-VAE params.
  in_resolution: 256 # Input Image Resolution
  out_resolution: 32 # Output/Latent space Resolution
  in_channels: 3
  z_channels: 3 # Latent channels
  out_channels: 3
  ch: 128 # First Convolution channel
  num_res_blocks: 2 # Number of Resnet Blocks at each level
  attn_resolution: 32 # Resolution to apply PixelAttention Blocks
  num_heads: 4 # Number of attention heads
  max_ch_multiplier: 4 # Maximum Channel Multiplier
  
  num_embed: 16384 # Vector Quantizer Codebook length
  embed_dim: 3 # Dim of each code in codebbok
  beta: 0.25 # Weight given to commitment loss.